export const listData = [
  {
    id: 1,
    rent: "$468.44",
    street: "63 Canary Lane",
    city: "Mingshui",
    duration: 16,
    contract_type: "Sublet",
    gender: "Female",
    picture: "http://dummyimage.com/184x100.png/5fa2dd/ffffff",
  },
  {
    id: 2,
    rent: "$1265.66",
    street: "0894 Ridge Oak Circle",
    city: "Menuma",
    duration: 59,
    contract_type: "Lease",
    gender: "Male",
    picture: "http://dummyimage.com/101x100.png/ff4444/ffffff",
  },
  {
    id: 3,
    rent: "$580.82",
    street: "335 Vahlen Lane",
    city: "Jõhvi",
    duration: 49,
    contract_type: "Sublet",
    gender: "Male",
    picture: "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
  },
  {
    id: 4,
    rent: "$612.28",
    street: "4651 Buena Vista Court",
    city: "Montpellier",
    duration: 52,
    contract_type: "Lease",
    gender: "Female",
    picture: "http://dummyimage.com/240x100.png/cc0000/ffffff",
  },
  {
    id: 5,
    rent: "$1434.83",
    street: "5934 Stoughton Parkway",
    city: "Argasari",
    duration: 13,
    contract_type: "Sublet",
    gender: "Genderfluid",
    picture: "http://dummyimage.com/141x100.png/5fa2dd/ffffff",
  },
  {
    id: 6,
    rent: "$534.36",
    street: "2 Parkside Hill",
    city: "Yazykovo",
    duration: 51,
    contract_type: "Sublet",
    gender: "Male",
    picture: "http://dummyimage.com/193x100.png/dddddd/000000",
  },
  {
    id: 7,
    rent: "$1989.56",
    street: "07615 Truax Lane",
    city: "Presidente Médici",
    duration: 33,
    contract_type: "Sublet",
    gender: "Female",
    picture: "http://dummyimage.com/148x100.png/5fa2dd/ffffff",
  },
  {
    id: 8,
    rent: "$1141.63",
    street: "58 Transport Place",
    city: "Sanandaj",
    duration: 11,
    contract_type: "Sublet",
    gender: "Non-binary",
    picture: "http://dummyimage.com/167x100.png/5fa2dd/ffffff",
  },
  {
    id: 9,
    rent: "$924.77",
    street: "4 Roth Avenue",
    city: "Wudangshan",
    duration: 60,
    contract_type: "Sublet",
    gender: "Male",
    picture: "http://dummyimage.com/229x100.png/ff4444/ffffff",
  },
  {
    id: 10,
    rent: "$1039.59",
    street: "844 Petterle Plaza",
    city: "San Francisco",
    duration: 32,
    contract_type: "Lease",
    gender: "Female",
    picture: "http://dummyimage.com/131x100.png/dddddd/000000",
  },
  {
    id: 11,
    rent: "$719.86",
    street: "29089 Grayhawk Circle",
    city: "Jubb Ramlah",
    duration: 37,
    contract_type: "Sublet",
    gender: "Male",
    picture: "http://dummyimage.com/119x100.png/cc0000/ffffff",
  },
  {
    id: 12,
    rent: "$911.04",
    street: "922 Division Terrace",
    city: "Repentigny",
    duration: 20,
    contract_type: "Lease",
    gender: "Male",
    picture: "http://dummyimage.com/163x100.png/5fa2dd/ffffff",
  },
];
